### ISSUE TITLE
Cannot build because of missing props.load(new FileInputStream(rootProject.file("project.properties")))

### ISSUE THREAD

**Issue by huuthe2002** [sgzsh269/android-mvp-with-dagger2#1]
ext.projectProps = {
    def props = new Properties()
    props.load(new FileInputStream(rootProject.file("project.properties")))
    project.ext.projectProps = props
}()

Build fails, please add project property file. 
Thanks advance

**Comment by sgzsh269** [comment]
@huuthe2002 I have added the `project.properties` file template to the root level, it basically just contains one field `flickrApiKey` which you have to initialize with your own Flickr API key.

Closing this ticket for now, let me know if you face any more issues.
